export const productsData = [
  {
    id: 1,
    title: "Men tie black",
    quantity: 1,
    description: "men tie bright black",
    availableSizes: ["L"],
    price: 50.9,
    isFreeShipping: true,
  },

  {
    id: 2,
    title: "Black Jeans",
    quantity: 1,
    description: "Plain black pants",
    availableSizes: ["S"],
    price: 100,
    isFreeShipping: false,
  },
  {
    id: 3,
    title: "Men sweater ",
    quantity: 1,
    description: "Coral sweater for men",
    availableSizes: ["L", "XL"],
    price: 210,
    isFreeShipping: true,
  },
  {
    id: 4,
    title: "Red VC bra",
    quantity: 1,
    description: "Victoria secret bra red",
    availableSizes: ["S", "M", "XL"],
    price: 76,
    isFreeShipping: true,
  },
  {
    id: 5,
    title: "TRX gloves",
    quantity: 1,
    description: "trx black and white gloves",
    availableSizes: ["XXL"],
    price: 23.1,
    isFreeShipping: false,
  },
  {
    id: 6,
    title: "Darker hat",
    quantity: 1,
    description: "dark gray hat for women",
    availableSizes: ["L", "S"],
    price: 10,
    isFreeShipping: true,
  },
  {
    id: 7,
    title: "Monkey T-shirt ",
    quantity: 1,
    description: "T-shirt with the pattern of monkey",
    availableSizes: ["M", "XL"],
    price: 23.4,
    isFreeShipping: true,
  },
];
